version: '2'
services:
  app:
    image: alpine
    volumes:
      # note: same as nginx, or else we get a mess when loading PHP files
      - ${APP_PATH}:${DESTINATION_PATH}:rw
    command: ['watch', '-n60', 'date']

  mysql:
    image: mysql:5
    volumes:
      - "${DATA_PATH}/mysql/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

  redis:
    image: redis:3.2-alpine
    volumes:
      - "${DATA_PATH}/redis:/data"
    command: redis-server --appendonly yes
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.6-management
    hostname: rabbitmq
    volumes:
      - "${DATA_PATH}/rabbitmq:/var/lib/rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
#      RABBITMQ_NODENAME: ${RABBITMQ_NODENAME}
    ports:
      - 15671:15671
      - 15672:15672
      - 5671:5671
      - 5672:5672

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  node:
    build:
      context: docker/node
      args:
        - DESTINATION_PATH
    links:
      - redis
      - rabbitmq
    volumes_from:
      - app:rw

# php 7.1
  php-fpm-7.1:
    build: docker/php-fpm-7.1
    links:
        - mysql
        - mailhog
        - redis
        - rabbitmq
    volumes:
      - "${DATA_PATH}/logs/php-fpm/7.1/:/var/log/php-fpm"
      - "${DATA_PATH}/logs/xdebug/7.1/:/var/log/xdebug"
    volumes_from:
      - app:rw

  php-fpm-debug-7.1:
    build: docker/php-fpm-debug-7.1
    links:
        - mysql
        - mailhog
        - redis
        - rabbitmq
    volumes:
      - "${DATA_PATH}/logs/php-fpm/7.1/:/var/log/php-fpm"
      - "${DATA_PATH}/logs/xdebug/7.1/:/var/log/xdebug"
    volumes_from:
      - app:rw
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_CONFIG: "remote_connect_back=0 remote_autostart=0 remote_host=${HOST_IP} idekey=${IDEKEY} remote_port=9000"

  php-cli-7.1:
    build:
      context: docker/php-cli-7.1
      args:
        - DESTINATION_PATH
    links:
        - mysql
        - mailhog
        - redis
        - rabbitmq
    volumes:
      - "${DATA_PATH}/logs/xdebug/7.1/:/var/log/xdebug"
    volumes_from:
      - app:rw
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_CONFIG: "remote_connect_back=0 remote_autostart=0 remote_host=${HOST_IP} idekey=docker-xdebug remote_port=9000"

# php 7.0
  php-fpm-7.0:
    build: docker/php-fpm-7.0
    links:
        - mysql
        - mailhog
        - redis
        - rabbitmq
    volumes:
      - "${DATA_PATH}/logs/php-fpm/7.0/:/var/log/php-fpm"
      - "${DATA_PATH}/logs/xdebug/7.0/:/var/log/xdebug"
    volumes_from:
      - app:rw

  php-fpm-debug-7.0:
    build: docker/php-fpm-debug-7.0
    links:
        - mysql
        - mailhog
        - redis
        - rabbitmq
    volumes:
      - "${DATA_PATH}/logs/php-fpm/7.0/:/var/log/php-fpm"
      - "${DATA_PATH}/logs/xdebug/7.0/:/var/log/xdebug"
    volumes_from:
      - app:rw
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_CONFIG: "remote_connect_back=0 remote_autostart=0 remote_host=${HOST_IP} idekey=docker-xdebug remote_port=9000"

  php-cli-7.0:
    build:
      context: docker/php-cli-7.0
      args:
        - DESTINATION_PATH
    links:
        - mysql
        - mailhog
        - redis
        - rabbitmq
    volumes:
      - "${DATA_PATH}/logs/xdebug/7.0/:/var/log/xdebug"
    volumes_from:
      - app:rw
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_CONFIG: "remote_connect_back=0 remote_autostart=0 remote_host=${HOST_IP} idekey=docker-xdebug remote_port=9000"

# php 5.6
  php-fpm-5.6:
    build: docker/php-fpm-5.6
    links:
        - mysql
        - mailhog
        - redis
        - rabbitmq
    volumes:
      - "${DATA_PATH}/logs/php-fpm/5.6/:/var/log/php-fpm"
      - "${DATA_PATH}/logs/xdebug/5.6/:/var/log/xdebug"
    volumes_from:
      - app:rw

  php-fpm-debug-5.6:
    build: docker/php-fpm-debug-5.6
    links:
        - mysql
        - mailhog
        - redis
        - rabbitmq
    volumes:
      - "${DATA_PATH}/logs/php-fpm/5.6/:/var/log/php-fpm"
      - "${DATA_PATH}/logs/xdebug/5.6/:/var/log/xdebug"
    volumes_from:
      - app:rw
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_CONFIG: "remote_connect_back=0 remote_autostart=0 remote_host=${HOST_IP} idekey=docker-xdebug remote_port=9000"

  php-cli-5.6:
    build:
      context: docker/php-cli-5.6
      args:
        - DESTINATION_PATH
    links:
        - mysql
        - mailhog
        - redis
        - rabbitmq
    volumes:
      - "${DATA_PATH}/logs/xdebug/5.6/:/var/log/xdebug"
    volumes_from:
      - app:rw
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_CONFIG: "remote_connect_back=0 remote_autostart=0 remote_host=${HOST_IP} idekey=docker-xdebug remote_port=9000"

  nginx:
    build:
      context: docker/nginx
      args:
        - NGINX_PROJECT_ROOT
        - NGINX_ENTRY_POINT_FILE
        - NGINX_ALLOWED_FILES

    ports:
      - 8071:8071
      - 9071:9071
      - 8070:8070
      - 9070:9070
      - 8056:8056
      - 9056:9056
    volumes:
      - "${DATA_PATH}/logs/nginx/:/var/log/nginx"
    volumes_from:
      - php-fpm-7.1
    links:
      - php-fpm-7.1
      - php-fpm-debug-7.1
      - php-fpm-7.0
      - php-fpm-debug-7.0
      - php-fpm-5.6
      - php-fpm-debug-5.6
    depends_on:
      - app
