# this is our development docker-compose building on top of the production docker-compose, just mounting
# the sync image - not redefining anything else

version: "2"
services:
  app:
    volumes:
      - docker-sync:${DESTINATION_PATH}:nocache

# that the important thing
volumes:
  docker-sync:
    external:
      name: "${SYNC_NAME}-sync"
